"""
Veritas_Core — DocumentGenerator: Learning Document Generator Tool.

A tool (not an agent) that takes a learning plan and generates
structured markdown learning documents.

Controlled by ResourceAgent through the Skill Router.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from core.contracts import LearningPlan, PlanNode


@dataclass
class DocumentSection:
    """A section within a learning document."""
    heading: str = ""
    level: int = 2                     # Markdown heading level
    content: str = ""
    subsections: List["DocumentSection"] = field(default_factory=list)

    def to_markdown(self) -> str:
        lines = [f"{'#' * self.level} {self.heading}", "", self.content, ""]
        for sub in self.subsections:
            lines.append(sub.to_markdown())
        return "\n".join(lines)


@dataclass
class GeneratedDocument:
    """Complete generated learning document."""
    title: str = ""
    plan_snapshot: Optional[LearningPlan] = None
    sections: List[DocumentSection] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_markdown(self) -> str:
        lines = [
            f"# {self.title}",
            "",
            f"> *Generated by Veritas-Core DocumentGenerator*",
            f"> *Date: {self.generated_at}*",
            "",
            "---",
            "",
        ]
        for section in self.sections:
            lines.append(section.to_markdown())
        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "sections": [
                {"heading": s.heading, "level": s.level}
                for s in self.sections
            ],
            "metadata": self.metadata,
            "generated_at": self.generated_at,
        }


class DocumentGenerator:
    """Generate structured markdown learning documents from plans.

    Usage:
        gen = DocumentGenerator()
        doc = gen.generate(learning_plan, profile_context)
        markdown_content = doc.to_markdown()
    """

    def generate(
        self,
        plan: LearningPlan,
        title: str = "Learning Document",
        profile_context: Optional[Dict[str, Any]] = None,
    ) -> GeneratedDocument:
        """Generate a complete learning document from a plan."""
        sections = self._build_sections(plan)

        doc = GeneratedDocument(
            title=title,
            plan_snapshot=plan,
            sections=sections,
            metadata={
                "node_count": len(plan.nodes),
                "total_minutes": plan.total_minutes,
                "strategy": plan.strategy_rationale,
                "profile_context": profile_context or {},
            },
        )
        return doc

    # ── section builders ──

    def _build_sections(self, plan: LearningPlan) -> List[DocumentSection]:
        sections: List[DocumentSection] = []

        # Overview section
        overview = self._build_overview(plan)
        sections.append(overview)

        # Learning path section
        path = self._build_learning_path(plan)
        sections.append(path)

        # Per-node sections
        for i, node in enumerate(plan.nodes):
            node_section = self._build_node_section(node, i + 1)
            sections.append(node_section)

        return sections

    def _build_overview(self, plan: LearningPlan) -> DocumentSection:
        strategy = plan.strategy_rationale or "Personalized learning plan"
        content = (
            f"**Total Duration**: {plan.total_minutes} minutes\n\n"
            f"**Strategy**: {strategy}\n\n"
            f"**Nodes**: {len(plan.nodes)} learning modules\n\n"
            f"This document was generated based on your learner profile "
            f"and knowledge assessment."
        )
        return DocumentSection(
            heading="Overview",
            level=2,
            content=content,
        )

    def _build_learning_path(self, plan: LearningPlan) -> DocumentSection:
        lines = ["| # | Module | Concepts | Depth | Time |", "|---|--------|----------|-------|------|"]
        for i, node in enumerate(plan.nodes):
            concepts = ", ".join(node.concepts[:3])
            lines.append(
                f"| {i+1} | {node.title} | {concepts} | {node.depth} | {node.estimated_minutes}min |"
            )

        return DocumentSection(
            heading="Learning Path",
            level=2,
            content="\n".join(lines),
        )

    def _build_node_section(self, node: PlanNode, index: int) -> DocumentSection:
        strategy_note = node.teaching_strategy or "standard"
        resource_list = ", ".join(node.resource_types) if node.resource_types else "notes"

        content = (
            f"**Level**: {node.level} | "
            f"**Depth**: {node.depth} | "
            f"**Estimated Time**: {node.estimated_minutes} minutes\n\n"
            f"**Key Concepts**: {', '.join(node.concepts)}\n\n"
            f"**Teaching Strategy**: {strategy_note}\n\n"
            f"**Resources**: {resource_list}\n\n"
            f"**Exercises**: {node.exercises_count} practice problems\n\n"
            f"*{node.rationale or ''}*\n"
        )

        return DocumentSection(
            heading=f"Module {index}: {node.title}",
            level=2,
            content=content,
        )
